name: binder_env
channels:
- defaults
dependencies:
- pandas=1.5.3
- python=3.9.16
- pip
- pip:
  - tensorflow==2.10.1
  - tensorboard==2.10.1
  - numpy==1.24.2
  - keras==2.10.0
  - scikit-learn==1.2.1
  - matplotlib==3.6.3
  - protobuf==3.19.6
